=== samirtenkoul/proyectosXML-DTD-XSD/E0_EjemploInicial2/4_0_EjemploInicial2.xsd
<?xml version = "1.0" encoding = "UTF-8"?> 
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">
	<xsd:element name = "alumno">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nombre" type="string"/>
				<xsd:element name="apellidos" type="string"/>
				<xsd:element name="direccion" type="string"/>
				<xsd:element name="CP" type="integer"/>
				<xsd:element name="edad" type="integer"/>
				<xsd:element name="ciclo_formativo" type="string"/>
				<xsd:element name="clave_ciclo" type="string"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== samirtenkoul/proyectosXML-DTD-XSD/E0_EjemploInicial2/4_0_EjemploInicial2.xml
<?xml version="1.0" encoding="UTF-8"?> 
<alumno 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="4_0_EjemploInicial2.xsd">  
	<nombre>Paco</nombre>  
	<apellidos>Seron</apellidos>  
	<direccion>Ayala</direccion>  
	<CP>28021</CP>  
	<edad>24</edad>  
	<ciclo_formativo>ASIR</ciclo_formativo>  
	<clave_ciclo>ASI123</clave_ciclo> 
</alumno>
